# Generated by Django 4.1.5 on 2023-05-06 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="brookuser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=20)),
                ("housename", models.CharField(max_length=30)),
                ("roadname", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=20)),
                ("state", models.CharField(max_length=20)),
                ("post", models.CharField(max_length=20)),
                ("pincode", models.CharField(max_length=6)),
                ("email", models.EmailField(max_length=40)),
                ("phone_number", models.CharField(max_length=10)),
                ("role", models.CharField(max_length=10)),
                ("userstatus", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=20, unique=True)),
                ("role", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=500)),
                ("complaint", models.CharField(max_length=500)),
                ("date", models.DateField()),
                ("replay", models.CharField(default="No Replay", max_length=500)),
                ("complaint_status", models.CharField(max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="brookwoodapp.brookuser",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="brookuser",
            name="log_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="brookwoodapp.log"
            ),
        ),
    ]
