# Generated by Django 4.1.5 on 2023-05-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brookwoodapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("GST", models.IntegerField()),
                ("product_price", models.IntegerField()),
                ("product_details", models.CharField(max_length=300)),
                ("image", models.ImageField(upload_to="images")),
                ("stock", models.CharField(max_length=500)),
                ("product_status", models.CharField(max_length=10)),
            ],
        ),
    ]
