# Generated by Django 4.1.5 on 2023-05-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brookwoodapp", "0002_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_price",
        ),
    ]
