# Generated by Django 4.1.5 on 2023-05-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brookwoodapp", "0003_remove_product_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_price",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
