# Generated by Django 4.1.5 on 2023-05-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brookwoodapp", "0003_rename_order_payment_orders_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="image",
            field=models.ImageField(default=1, upload_to="images"),
            preserve_default=False,
        ),
    ]
