# Generated by Django 4.1.5 on 2023-05-14 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("brookwoodapp", "0004_cart_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="brookwoodapp.product"
            ),
        ),
    ]
