# Generated by Django 4.1.5 on 2023-05-14 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("brookwoodapp", "0005_alter_complaint_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="brookwoodapp.product",
            ),
            preserve_default=False,
        ),
    ]
