# Generated by Django 4.1.5 on 2023-05-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brookwoodapp", "0007_cart_p_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="price",
            new_name="total_price",
        ),
        migrations.AddField(
            model_name="order",
            name="category",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="order",
            name="product_name",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
