# Generated by Django 4.1.5 on 2023-05-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brookwoodapp", "0009_alter_order_category_alter_order_order_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_price",
            name="price_status",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
